'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property padding_root() As Integer
            Get
                Return CType(Me("padding_root"),Integer)
            End Get
            Set
                Me("padding_root") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("rtl")>  _
        Public Property direction() As String
            Get
                Return CType(Me("direction"),String)
            End Get
            Set
                Me("direction") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property padding_top_h1() As Integer
            Get
                Return CType(Me("padding_top_h1"),Integer)
            End Get
            Set
                Me("padding_top_h1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property padding_bottom_h1() As Integer
            Get
                Return CType(Me("padding_bottom_h1"),Integer)
            End Get
            Set
                Me("padding_bottom_h1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("center")>  _
        Public Property text_align_h1() As String
            Get
                Return CType(Me("text_align_h1"),String)
            End Get
            Set
                Me("text_align_h1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("22")>  _
        Public Property font_size_h1() As Integer
            Get
                Return CType(Me("font_size_h1"),Integer)
            End Get
            Set
                Me("font_size_h1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("700")>  _
        Public Property font_weight_h1() As Integer
            Get
                Return CType(Me("font_weight_h1"),Integer)
            End Get
            Set
                Me("font_weight_h1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tahoma")>  _
        Public Property font_family_h1() As String
            Get
                Return CType(Me("font_family_h1"),String)
            End Get
            Set
                Me("font_family_h1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property padding_top_h4() As String
            Get
                Return CType(Me("padding_top_h4"),String)
            End Get
            Set
                Me("padding_top_h4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property padding_bottom_h4() As String
            Get
                Return CType(Me("padding_bottom_h4"),String)
            End Get
            Set
                Me("padding_bottom_h4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public Property font_size_h4() As String
            Get
                Return CType(Me("font_size_h4"),String)
            End Get
            Set
                Me("font_size_h4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property font_weight_h4() As String
            Get
                Return CType(Me("font_weight_h4"),String)
            End Get
            Set
                Me("font_weight_h4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tahoma")>  _
        Public Property font_family_h4() As String
            Get
                Return CType(Me("font_family_h4"),String)
            End Get
            Set
                Me("font_family_h4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property padding_top_h5() As String
            Get
                Return CType(Me("padding_top_h5"),String)
            End Get
            Set
                Me("padding_top_h5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property padding_bottom_h5() As String
            Get
                Return CType(Me("padding_bottom_h5"),String)
            End Get
            Set
                Me("padding_bottom_h5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public Property font_size_h5() As String
            Get
                Return CType(Me("font_size_h5"),String)
            End Get
            Set
                Me("font_size_h5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property font_weight_h5() As String
            Get
                Return CType(Me("font_weight_h5"),String)
            End Get
            Set
                Me("font_weight_h5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tahoma")>  _
        Public Property font_family_h5() As String
            Get
                Return CType(Me("font_family_h5"),String)
            End Get
            Set
                Me("font_family_h5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property margin_div_one_top() As String
            Get
                Return CType(Me("margin_div_one_top"),String)
            End Get
            Set
                Me("margin_div_one_top") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property margin_div_one_bottom() As String
            Get
                Return CType(Me("margin_div_one_bottom"),String)
            End Get
            Set
                Me("margin_div_one_bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property padding_div_tow_top() As String
            Get
                Return CType(Me("padding_div_tow_top"),String)
            End Get
            Set
                Me("padding_div_tow_top") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property padding_div_tow_bottom() As String
            Get
                Return CType(Me("padding_div_tow_bottom"),String)
            End Get
            Set
                Me("padding_div_tow_bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property margin_div_thre_top() As String
            Get
                Return CType(Me("margin_div_thre_top"),String)
            End Get
            Set
                Me("margin_div_thre_top") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property margin_div_thre_bottom() As String
            Get
                Return CType(Me("margin_div_thre_bottom"),String)
            End Get
            Set
                Me("margin_div_thre_bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property padding_div_four_top() As String
            Get
                Return CType(Me("padding_div_four_top"),String)
            End Get
            Set
                Me("padding_div_four_top") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property padding_div_four_bottom() As String
            Get
                Return CType(Me("padding_div_four_bottom"),String)
            End Get
            Set
                Me("padding_div_four_bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property img_top_height() As String
            Get
                Return CType(Me("img_top_height"),String)
            End Get
            Set
                Me("img_top_height") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property img_log_height() As String
            Get
                Return CType(Me("img_log_height"),String)
            End Get
            Set
                Me("img_log_height") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property img_log_width() As String
            Get
                Return CType(Me("img_log_width"),String)
            End Get
            Set
                Me("img_log_width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property img_footer_height() As String
            Get
                Return CType(Me("img_footer_height"),String)
            End Get
            Set
                Me("img_footer_height") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property padding_p_one_top() As String
            Get
                Return CType(Me("padding_p_one_top"),String)
            End Get
            Set
                Me("padding_p_one_top") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property padding_p_one_bottom() As String
            Get
                Return CType(Me("padding_p_one_bottom"),String)
            End Get
            Set
                Me("padding_p_one_bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public Property font_size_p_one() As String
            Get
                Return CType(Me("font_size_p_one"),String)
            End Get
            Set
                Me("font_size_p_one") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tahoma")>  _
        Public Property font_family_p_one() As String
            Get
                Return CType(Me("font_family_p_one"),String)
            End Get
            Set
                Me("font_family_p_one") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property padding_p_tow_top() As String
            Get
                Return CType(Me("padding_p_tow_top"),String)
            End Get
            Set
                Me("padding_p_tow_top") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property padding_p_tow_bottom() As String
            Get
                Return CType(Me("padding_p_tow_bottom"),String)
            End Get
            Set
                Me("padding_p_tow_bottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public Property font_size_p_tow() As String
            Get
                Return CType(Me("font_size_p_tow"),String)
            End Get
            Set
                Me("font_size_p_tow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tahoma")>  _
        Public Property font_family_p_tow() As String
            Get
                Return CType(Me("font_family_p_tow"),String)
            End Get
            Set
                Me("font_family_p_tow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public Property font_size_table() As String
            Get
                Return CType(Me("font_size_table"),String)
            End Get
            Set
                Me("font_size_table") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tahoma")>  _
        Public Property font_family_table() As String
            Get
                Return CType(Me("font_family_table"),String)
            End Get
            Set
                Me("font_family_table") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property margin_top_table_one() As String
            Get
                Return CType(Me("margin_top_table_one"),String)
            End Get
            Set
                Me("margin_top_table_one") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property border_table_one() As String
            Get
                Return CType(Me("border_table_one"),String)
            End Get
            Set
                Me("border_table_one") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property height_table_one() As String
            Get
                Return CType(Me("height_table_one"),String)
            End Get
            Set
                Me("height_table_one") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property border_table_tow() As String
            Get
                Return CType(Me("border_table_tow"),String)
            End Get
            Set
                Me("border_table_tow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("128, 255, 128")>  _
        Public Property th_tow_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("th_tow_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("th_tow_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property th_tow_border() As String
            Get
                Return CType(Me("th_tow_border"),String)
            End Get
            Set
                Me("th_tow_border") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property td_tow_border() As String
            Get
                Return CType(Me("td_tow_border"),String)
            End Get
            Set
                Me("td_tow_border") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property tr_tow_border() As String
            Get
                Return CType(Me("tr_tow_border"),String)
            End Get
            Set
                Me("tr_tow_border") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("224, 224, 224")>  _
        Public Property tr_tow_color() As Global.System.Drawing.Color
            Get
                Return CType(Me("tr_tow_color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("tr_tow_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property all_row() As String
            Get
                Return CType(Me("all_row"),String)
            End Get
            Set
                Me("all_row") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property hedar() As String
            Get
                Return CType(Me("hedar"),String)
            End Get
            Set
                Me("hedar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property footer() As String
            Get
                Return CType(Me("footer"),String)
            End Get
            Set
                Me("footer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property line1() As String
            Get
                Return CType(Me("line1"),String)
            End Get
            Set
                Me("line1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property line2() As String
            Get
                Return CType(Me("line2"),String)
            End Get
            Set
                Me("line2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property line3() As String
            Get
                Return CType(Me("line3"),String)
            End Get
            Set
                Me("line3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property text_p_one_align() As String
            Get
                Return CType(Me("text_p_one_align"),String)
            End Get
            Set
                Me("text_p_one_align") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property font_weight_p_one() As String
            Get
                Return CType(Me("font_weight_p_one"),String)
            End Get
            Set
                Me("font_weight_p_one") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property font_weight_p_tow() As String
            Get
                Return CType(Me("font_weight_p_tow"),String)
            End Get
            Set
                Me("font_weight_p_tow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property webbrowser() As String
            Get
                Return CType(Me("webbrowser"),String)
            End Get
            Set
                Me("webbrowser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property printer() As String
            Get
                Return CType(Me("printer"),String)
            End Get
            Set
                Me("printer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property border_div_four() As String
            Get
                Return CType(Me("border_div_four"),String)
            End Get
            Set
                Me("border_div_four") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property page_width() As String
            Get
                Return CType(Me("page_width"),String)
            End Get
            Set
                Me("page_width") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.s_print.My.MySettings
            Get
                Return Global.s_print.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
